# Traitement du dataset

In [1]:
import numpy as np
import pandas as pd
import datetime

In [30]:
data= pd.read_csv("/Users/mac/Documents/OPENOPSE/data/Sidy Sow/OutdataFFlux_OpenOPSE_LAI.csv")
data.head()

,Leaf_Fa_1_pc,Leaf_Fa_2_pc,Leaf_Fa_3_pc,Leaf_Fa_4_pc,Leaf_Fa_5_pc,Leaf_Fa_6_pc,Leaf_Fa_7_pc,Leaf_Fa_8_pc,Leaf_Fa_9_pc,Leaf_Fa_10_pc,...,DripLineLAI_Fa_10_m2leafm2,DripLineLAI_Fa_11_m2leafm2,DripLineLAI_Fa_12_m2leafm2,DripLineLAI_Fa_27_m2leafm2,DripLineLAI_Fa_28_m2leafm2,DripLineLAI_Fa_46_m2leafm2,Mean_Tree_LAI_Towerplot_m2leafm2,CropWeedNDVI,CropWeedLAI,TreeandCropWeedLAI_m2leafm2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [32]:
data1= pd.read_csv("/Users/mac/Documents/OPENOPSE/data/Frederic Do/data/OutdataFFlux_OpenOPSE_DeepSoilTempElectCondHumidPot.csv")
data['DateSemih'] = data1['DateSemih']

In [40]:
data.to_csv("/Users/mac/Documents/OPENOPSE/data/Sidy Sow/OutdataFFlux_OpenOPSE_LAI.csv", index=False)

In [33]:
annees = [x.split('-',1)[0] for x in data.DateSemih]
data.index= annees
data.head()

,Leaf_Fa_1_pc,Leaf_Fa_2_pc,Leaf_Fa_3_pc,Leaf_Fa_4_pc,Leaf_Fa_5_pc,Leaf_Fa_6_pc,Leaf_Fa_7_pc,Leaf_Fa_8_pc,Leaf_Fa_9_pc,Leaf_Fa_10_pc,...,DripLineLAI_Fa_11_m2leafm2,DripLineLAI_Fa_12_m2leafm2,DripLineLAI_Fa_27_m2leafm2,DripLineLAI_Fa_28_m2leafm2,DripLineLAI_Fa_46_m2leafm2,Mean_Tree_LAI_Towerplot_m2leafm2,CropWeedNDVI,CropWeedLAI,TreeandCropWeedLAI_m2leafm2,DateSemih
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 00:15:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 00:45:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 01:15:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 01:45:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 02:15:00

In [34]:
annees = [x.split('-',1)[0] for x in data.DateSemih]
data['Year']= annees
data=data.astype({'Year': 'int64'})

In [35]:
Date_fac = [x.split(' ',1)[0] for x in data.DateSemih]
data['Date_fac']= Date_fac

In [36]:
Hour_fac = [x.split(' ',1)[1] for x in data.DateSemih]
data['Hour_fac']= Hour_fac

In [37]:
data.head()

,Leaf_Fa_1_pc,Leaf_Fa_2_pc,Leaf_Fa_3_pc,Leaf_Fa_4_pc,Leaf_Fa_5_pc,Leaf_Fa_6_pc,Leaf_Fa_7_pc,Leaf_Fa_8_pc,Leaf_Fa_9_pc,Leaf_Fa_10_pc,...,DripLineLAI_Fa_28_m2leafm2,DripLineLAI_Fa_46_m2leafm2,Mean_Tree_LAI_Towerplot_m2leafm2,CropWeedNDVI,CropWeedLAI,TreeandCropWeedLAI_m2leafm2,DateSemih,Year,Date_fac,Hour_fac
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 00:15:00,2018,2018-01-01,00:15:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 00:45:00,2018,2018-01-01,00:45:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 01:15:00,2018,2018-01-01,01:15:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 01:45:00,2018,2018-01-01,01:45:00
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,2018-01-01 02:15:00,2018,2018-01-01,02:15:00

# creation des dataframe

## segmentation du jeu de donnÃ©es

In [38]:
annee = data['Year'].unique()
annee

array([2018, 2019, 2020, 2021, 2022])

## sauvegarder les jeux de donnÃ©es segmentÃ©s

In [39]:
for y in annee:
    save = data[data['Year'] == y]
    name = '/Users/mac/Documents/OPENOPSE/data/Sidy Sow/segments/csv/OutdataFFlux_OpenOPSE_LAI_'+str(y)+'.csv'
    save.to_csv(name, index=False)